version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: max
      POSTGRES_PASSWORD: jbfgslgsdlfkngd
      POSTGRES_DB: posts
      POSTGRES_PORT: 5432
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 3200:5432
    # network_mode: "host"
  
  scanner-impuls:
    restart: always
    build:
      context: .
      dockerfile: vk-scanner/Dockerfile
    environment:
      DATABASE_POOL_MAX: 40
      DATABASE_POOL_MIN: 5
      DATABASE_URL: postgres://max:jbfgslgsdlfkngd@localhost:3200/posts
      DATABASE_SCHEMA: public
      SOURCE_KEY: IMPULS
    depends_on:
      - db
    network_mode: "host"
  
  scanner-hse:
    restart: always
    build:
      context: .
      dockerfile: vk-scanner/Dockerfile
    environment:
      DATABASE_POOL_MAX: 40
      DATABASE_POOL_MIN: 5
      DATABASE_URL: postgres://max:jbfgslgsdlfkngd@localhost:3200/posts
      DATABASE_SCHEMA: public
      SOURCE_KEY: HSE
    depends_on:
      - db
    network_mode: "host"
  
  scanner-bmstu:
    restart: always
    build:
      context: .
      dockerfile: vk-scanner/Dockerfile
    environment:
      DATABASE_POOL_MAX: 40
      DATABASE_POOL_MIN: 5
      DATABASE_URL: postgres://max:jbfgslgsdlfkngd@localhost:3200/posts
      DATABASE_SCHEMA: public
      SOURCE_KEY: BMSTU
    depends_on:
      - db
    network_mode: "host"
  
  scanner-innopolis:
    restart: always
    build:
      context: .
      dockerfile: vk-scanner/Dockerfile
    environment:
      DATABASE_POOL_MAX: 40
      DATABASE_POOL_MIN: 5
      DATABASE_URL: postgres://max:jbfgslgsdlfkngd@localhost:3200/posts
      DATABASE_SCHEMA: public
      SOURCE_KEY: INNOPOLIS
    depends_on:
      - db
    network_mode: "host"

  backend:
    restart: always
    build:
      context: .
      dockerfile: server/Dockerfile
    environment:
      DATABASE_POOL_MAX: 50
      DATABASE_POOL_MIN: 5
      DATABASE_SCHEMA: public
      DATABASE_URL: postgres://max:jbfgslgsdlfkngd@localhost:3200/posts
    depends_on:
      - db
    network_mode: "host"
  
  frontend:
    restart: always
    build:
      context: .
      dockerfile: site/.ci/Dockerfile
    network_mode: "host"
  
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    network_mode: "host"
  
  webserver:
    build:
      context: .
      dockerfile: nginx/.ci/Dockerfile
    restart: always
    volumes:
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    network_mode: "host"