version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: max
      POSTGRES_PASSWORD: jbfgslgsdlfkngd
      POSTGRES_DB: posts
      POSTGRES_PORT: 5432
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 3200:5432
    networks:
      - mynetwork
  
  scanner-impuls:
    restart: always
    build:
      context: .
      dockerfile: vk-scanner/Dockerfile
    environment:
      DATABASE_POOL_MAX: 40
      DATABASE_POOL_MIN: 5
      DATABASE_URL: postgres://max:jbfgslgsdlfkngd@db:5432/posts
      DATABASE_SCHEMA: public
      SOURCE_KEY: IMPULS
    depends_on:
      - db
    networks:
      - mynetwork
  
  scanner-hse:
    restart: always
    build:
      context: .
      dockerfile: vk-scanner/Dockerfile
    environment:
      DATABASE_POOL_MAX: 40
      DATABASE_POOL_MIN: 5
      DATABASE_URL: postgres://max:jbfgslgsdlfkngd@db:5432/posts
      DATABASE_SCHEMA: public
      SOURCE_KEY: HSE
    depends_on:
      - db
    networks:
      - mynetwork
  
  scanner-bmstu:
    restart: always
    build:
      context: .
      dockerfile: vk-scanner/Dockerfile
    environment:
      DATABASE_POOL_MAX: 40
      DATABASE_POOL_MIN: 5
      DATABASE_URL: postgres://max:jbfgslgsdlfkngd@db:5432/posts
      DATABASE_SCHEMA: public
      SOURCE_KEY: BMSTU
    depends_on:
      - db
    networks:
      - mynetwork

  site:
    restart: always
    build:
      context: .
      dockerfile: server/Dockerfile
    environment:
      DATABASE_POOL_MAX: 50
      DATABASE_POOL_MIN: 5
      DATABASE_SCHEMA: public
      DATABASE_URL: postgres://max:jbfgslgsdlfkngd@db:5432/posts
    depends_on:
      - db
    networks:
      - mynetwork
    ports:
      - 8000:8000

networks:
  mynetwork: