version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: max
      POSTGRES_PASSWORD: jbfgslgsdlfkngd
      POSTGRES_DB: posts
      POSTGRES_PORT: 5432
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 3200:5432
    # network_mode: "host"
  
  scanner-impuls:
    restart: always
    build:
      context: .
      dockerfile: vk-scanner/Dockerfile
    environment:
      DATABASE_POOL_MAX: 40
      DATABASE_POOL_MIN: 5
      DATABASE_URL: postgres://max:jbfgslgsdlfkngd@localhost:3200/posts
      DATABASE_SCHEMA: public
      SOURCE_KEY: IMPULS
      SOURCE_URL: https://vk.com/impulse131
      RESTART_TIME: 3
    depends_on:
      - db
    network_mode: "host"
  
  scanner-hse:
    restart: always
    build:
      context: .
      dockerfile: vk-scanner/Dockerfile
    environment:
      DATABASE_POOL_MAX: 40
      DATABASE_POOL_MIN: 5
      DATABASE_URL: postgres://max:jbfgslgsdlfkngd@localhost:3200/posts
      DATABASE_SCHEMA: public
      SOURCE_KEY: HSE
      SOURCE_URL: https://vk.com/hseolymp
      RESTART_TIME: 3
    depends_on:
      - db
    network_mode: "host"
  
  scanner-bmstu:
    restart: always
    build:
      context: .
      dockerfile: vk-scanner/Dockerfile
    environment:
      DATABASE_POOL_MAX: 40
      DATABASE_POOL_MIN: 5
      DATABASE_URL: postgres://max:jbfgslgsdlfkngd@localhost:3200/posts
      DATABASE_SCHEMA: public
      SOURCE_KEY: BMSTU
      SOURCE_URL: https://vk.com/olymp_bmstu
      RESTART_TIME: 3
    depends_on:
      - db
    network_mode: "host"
  
  scanner-innopolis:
    restart: always
    build:
      context: .
      dockerfile: vk-scanner/Dockerfile
    environment:
      DATABASE_POOL_MAX: 40
      DATABASE_POOL_MIN: 5
      DATABASE_URL: postgres://max:jbfgslgsdlfkngd@localhost:3200/posts
      DATABASE_SCHEMA: public
      SOURCE_KEY: INNOPOLIS
      SOURCE_URL: https://vk.com/innopolisu
      RESTART_TIME: 3
    depends_on:
      - db
    network_mode: "host"
  
  scanner-special:
    restart: always
    build:
      context: .
      dockerfile: vk-scanner/Dockerfile
    environment:
      DATABASE_POOL_MAX: 40
      DATABASE_POOL_MIN: 5
      DATABASE_URL: postgres://max:jbfgslgsdlfkngd@localhost:3200/posts
      DATABASE_SCHEMA: public
      SOURCE_KEY: SPECIAL
      SOURCE_URL: https://vk.com/club224926448
      RESTART_TIME: 3
    depends_on:
      - db
    network_mode: "host"
  
  scanner-distolymp:
    restart: always
    build:
      context: .
      dockerfile: vk-scanner/Dockerfile
    environment:
      DATABASE_POOL_MAX: 40
      DATABASE_POOL_MIN: 5
      DATABASE_URL: postgres://max:jbfgslgsdlfkngd@localhost:3200/posts
      DATABASE_SCHEMA: public
      SOURCE_KEY: DISTOLYMP
      SOURCE_URL: https://vk.com/distolymp
      RESTART_TIME: 3
    depends_on:
      - db
    network_mode: "host"
  
  scanner-lomonosov-olymp:
    restart: always
    build:
      context: .
      dockerfile: vk-scanner/Dockerfile
    environment:
      DATABASE_POOL_MAX: 40
      DATABASE_POOL_MIN: 5
      DATABASE_URL: postgres://max:jbfgslgsdlfkngd@localhost:3200/posts
      DATABASE_SCHEMA: public
      SOURCE_KEY: LOMONOSOV_OLYMP_CHEMISTRY
      SOURCE_URL: https://vk.com/lomonosov.olymp
      RESTART_TIME: 3
    depends_on:
      - db
    network_mode: "host"
  
  scanner-olympspbu:
    restart: always
    build:
      context: .
      dockerfile: vk-scanner/Dockerfile
    environment:
      DATABASE_POOL_MAX: 40
      DATABASE_POOL_MIN: 5
      DATABASE_URL: postgres://max:jbfgslgsdlfkngd@localhost:3200/posts
      DATABASE_SCHEMA: public
      SOURCE_KEY: OLYMP_SPBU
      SOURCE_URL: https://vk.com/olympspbu
      RESTART_TIME: 3
    depends_on:
      - db
    network_mode: "host"
  
  scanner-innopolis-open-is:
    restart: always
    build:
      context: .
      dockerfile: vk-scanner/Dockerfile
    environment:
      DATABASE_POOL_MAX: 40
      DATABASE_POOL_MIN: 5
      DATABASE_URL: postgres://max:jbfgslgsdlfkngd@localhost:3200/posts
      DATABASE_SCHEMA: public
      SOURCE_KEY: INNOPOLIS_OPEN_IS
      SOURCE_URL: https://vk.com/iuiso
      RESTART_TIME: 3
    depends_on:
      - db
    network_mode: "host"
  
  scanner-olymp-gazprom:
    restart: always
    build:
      context: .
      dockerfile: vk-scanner/Dockerfile
    environment:
      DATABASE_POOL_MAX: 40
      DATABASE_POOL_MIN: 5
      DATABASE_URL: postgres://max:jbfgslgsdlfkngd@localhost:3200/posts
      DATABASE_SCHEMA: public
      SOURCE_KEY: OLYMP_GAZPROM
      SOURCE_URL: https://vk.com/olymp_gazprom
      RESTART_TIME: 3
    depends_on:
      - db
    network_mode: "host"
  
  scanner-olymp-nti:
    restart: always
    build:
      context: .
      dockerfile: vk-scanner/Dockerfile
    environment:
      DATABASE_POOL_MAX: 40
      DATABASE_POOL_MIN: 5
      DATABASE_URL: postgres://max:jbfgslgsdlfkngd@localhost:3200/posts
      DATABASE_SCHEMA: public
      SOURCE_KEY: OLYMP_NTI
      SOURCE_URL: https://vk.com/nticontest
      RESTART_TIME: 3
    depends_on:
      - db
    network_mode: "host"
  
  scanner-about-project:
    restart: always
    build:
      context: .
      dockerfile: vk-scanner/Dockerfile
    environment:
      DATABASE_POOL_MAX: 40
      DATABASE_POOL_MIN: 5
      DATABASE_URL: postgres://max:jbfgslgsdlfkngd@localhost:3200/posts
      DATABASE_SCHEMA: public
      SOURCE_KEY: ABOUT_PROJECT
      SOURCE_URL: https://vk.com/club225033050
      RESTART_TIME: 3
    depends_on:
      - db
    network_mode: "host"

  backend:
    restart: always
    build:
      context: .
      dockerfile: server/Dockerfile
    environment:
      DATABASE_POOL_MAX: 50
      DATABASE_POOL_MIN: 5
      DATABASE_SCHEMA: public
      DATABASE_URL: postgres://max:jbfgslgsdlfkngd@localhost:3200/posts
    depends_on:
      - db
    network_mode: "host"
  
  frontend:
    restart: always
    environment:
      API_HOST: '/'
    build:
      context: .
      dockerfile: site/.ci/Dockerfile
    network_mode: "host"
  
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    network_mode: "host"
  
  nginx:
    build:
      context: .
      dockerfile: nginx/.ci/Dockerfile
    restart: always
    volumes:
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    network_mode: "host"